/*
	ACAccountAuthorizationAPIExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "ACAccountAuthorizationAPIExample.h"
#import "ACAccountAuthorizationAPI.h"

@implementation ACAccountAuthorizationAPIExample

- (void)run {
	// Create the service
	ACAccountAuthorizationAPI* service = [ACAccountAuthorizationAPI service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns ACAuthorizationResponse*. 
	[service AuthenticateAccount:self action:@selector(AuthenticateAccountHandler:) apiKey: @"" emailAddress: @"" password: @""];

	// Returns ACAuthorizationResponse*. 
	[service CreateAccount:self action:@selector(CreateAccountHandler:) apiKey: @"" emailAddress: @"" password: @""];
}

	

// Handle the response from AuthenticateAccount.
		
- (void) AuthenticateAccountHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACAuthorizationResponse* result
		ACAuthorizationResponse* result = (ACAuthorizationResponse*)value;
	NSLog(@"AuthenticateAccount returned the value: %@", result);
			
}
	

// Handle the response from CreateAccount.
		
- (void) CreateAccountHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACAuthorizationResponse* result
		ACAuthorizationResponse* result = (ACAuthorizationResponse*)value;
	NSLog(@"CreateAccount returned the value: %@", result);
			
}
	

@end
		