/*
	ACAccountAuthorizationAPIExample.h
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
@interface ACAccountAuthorizationAPIExample : NSObject {
}
-(void)run;
@end
		