/*
	ACECommerceAPIExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "ACECommerceAPIExample.h"
#import "ACECommerceAPI.h"

@implementation ACECommerceAPIExample

- (void)run {
	// Create the service
	ACECommerceAPI* service = [ACECommerceAPI service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns ACCartResponse*. 
	[service CartAddItem:self action:@selector(CartAddItemHandler:) apiKey: @"" applicationId: @"" sessionId: @"" itemId: @"" lookupType: @"" quantity: 0];

	// Returns ACShippingOptionResponse*. 
	[service CartGetShippingOptions:self action:@selector(CartGetShippingOptionsHandler:) apiKey: @"" applicationId: @"" sessionId: @""];

	// Returns ACOrderResponse*. 
	[service CartSubmitForOrder:self action:@selector(CartSubmitForOrderHandler:) apiKey: @"" applicationId: @"" sessionId: @""];

	// Returns ACCartResponse*. 
	[service CartUpdateCartItemQuantity:self action:@selector(CartUpdateCartItemQuantityHandler:) apiKey: @"" applicationId: @"" sessionId: @"" cartItemId: @"" quantity: 0];

	// Returns ACCartResponse*. 
	[service CartUpdateShipmentPriority:self action:@selector(CartUpdateShipmentPriorityHandler:) apiKey: @"" applicationId: @"" sessionId: @"" shipmentPriority: @""];

	// Returns ACCartResponse*. 
	[service CartUpdateShippingAddress:self action:@selector(CartUpdateShippingAddressHandler:) apiKey: @"" applicationId: @"" sessionId: @"" firstName: @"" lastName: @"" addressLine1: @"" addressLine2: @"" companyName: @"" city: @"" state: @"" twoDigitIsoCountryCode: @"" zipCode: @"" primaryPhone: @"" secondaryPhone: @"" emailAddress: @""];

	// Returns ACFeaturedCategoryResponse*. 
	[service CatalogGetFeaturedCategories:self action:@selector(CatalogGetFeaturedCategoriesHandler:) apiKey: @"" applicationId: @"" sessionId: @""];

	// Returns ACItemResponse*. 
	[service CatalogItemGet:self action:@selector(CatalogItemGetHandler:) apiKey: @"" applicationId: @"" sessionId: @"" itemId: @"" lookupType: @""];

	// Returns ACItemResponse*. 
	[service CatalogItemGetFrameRecommendations:self action:@selector(CatalogItemGetFrameRecommendationsHandler:) apiKey: @"" applicationId: @"" sessionId: @"" itemId: @"" lookupType: @"" maxNumberOfRecommendations: 0 maxJpegImageWidth: 0 maxJpegImageHeight: 0];

	// Returns ACItemSearchResponse*. 
	[service CatalogItemSearch:self action:@selector(CatalogItemSearchHandler:) apiKey: @"" applicationId: @"" sessionId: @"" searchText: @"" categoryIdList: @"" artistCategoryId: 0 numberOfRecords: 0 pageNumber: 0 sortBy: @"" sortDirection: @""];

	// Returns ACItemSearchResponse*. 
	[service CatalogItemSearchByImage:self action:@selector(CatalogItemSearchByImageHandler:) apiKey: @"" applicationId: @"" sessionId: @"" imageUrl: @"" numberOfRecords: 0 pageNumbers: 0];

	// Returns ACGalleryDetailResponse*. 
	[service GalleryAddForUser:self action:@selector(GalleryAddForUserHandler:) apiKey: @"" authToken: @"" galleryName: @"" galleryVisibility: @""];

	// Returns ACGalleryDetailResponse*. 
	[service GalleryAddItem:self action:@selector(GalleryAddItemHandler:) apiKey: @"" authToken: @"" galleryId: @"" itemId: @"" lookupType: @""];

	// Returns ACGalleryDetailResponse*. 
	[service GalleryAddWallImageByImageGUID:self action:@selector(GalleryAddWallImageByImageGUIDHandler:) apiKey: @"" authToken: @"" galleryId: @"" wallName: @"" wallImageGuid: @"" wallAreaWidth: [NSDecimalNumber numberWithInt:0] wallAreaHeight: [NSDecimalNumber numberWithInt:0] wallAreaWidthInches: [NSDecimalNumber numberWithInt:0] wallAreaHeightInches: [NSDecimalNumber numberWithInt:0] rulerX1: [NSDecimalNumber numberWithInt:0] rulerX2: [NSDecimalNumber numberWithInt:0] rulerY1: [NSDecimalNumber numberWithInt:0] rulerY2: [NSDecimalNumber numberWithInt:0] rulerLength: [NSDecimalNumber numberWithInt:0] caption: @""];

	// Returns ACGalleryDetailResponse*. 
	[service GalleryGet:self action:@selector(GalleryGetHandler:) apiKey: @"" galleryId: @""];

	// Returns ACGalleryListResponse*. 
	[service GalleryGetByUser:self action:@selector(GalleryGetByUserHandler:) apiKey: @"" authToken: @""];

	// Returns ACGalleryDetailResponse*. 
	[service GalleryGetUserDefaultMobileGallery:self action:@selector(GalleryGetUserDefaultMobileGalleryHandler:) apiKey: @"" authToken: @""];

	// Returns ACGalleryDetailResponse*. 
	[service GalleryGetUserDefaultWallGallery:self action:@selector(GalleryGetUserDefaultWallGalleryHandler:) apiKey: @"" authToken: @""];

	// Returns ACGalleryDetailResponse*. 
	[service GalleryRemoveItem:self action:@selector(GalleryRemoveItemHandler:) apiKey: @"" authToken: @"" galleryId: @"" galleryItemId: @""];

	// Returns ACSessionResponse*. 
	[service InitializeAPI:self action:@selector(InitializeAPIHandler:) apiKey: @"" applicationId: @"" twoDigitISOCountryCode: @"" twoDigitISOLanguageCode: @""];
}

	

// Handle the response from CartAddItem.
		
- (void) CartAddItemHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACCartResponse* result
		ACCartResponse* result = (ACCartResponse*)value;
	NSLog(@"CartAddItem returned the value: %@", result);
			
}
	

// Handle the response from CartGetShippingOptions.
		
- (void) CartGetShippingOptionsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACShippingOptionResponse* result
		ACShippingOptionResponse* result = (ACShippingOptionResponse*)value;
	NSLog(@"CartGetShippingOptions returned the value: %@", result);
			
}
	

// Handle the response from CartSubmitForOrder.
		
- (void) CartSubmitForOrderHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACOrderResponse* result
		ACOrderResponse* result = (ACOrderResponse*)value;
	NSLog(@"CartSubmitForOrder returned the value: %@", result);
			
}
	

// Handle the response from CartUpdateCartItemQuantity.
		
- (void) CartUpdateCartItemQuantityHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACCartResponse* result
		ACCartResponse* result = (ACCartResponse*)value;
	NSLog(@"CartUpdateCartItemQuantity returned the value: %@", result);
			
}
	

// Handle the response from CartUpdateShipmentPriority.
		
- (void) CartUpdateShipmentPriorityHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACCartResponse* result
		ACCartResponse* result = (ACCartResponse*)value;
	NSLog(@"CartUpdateShipmentPriority returned the value: %@", result);
			
}
	

// Handle the response from CartUpdateShippingAddress.
		
- (void) CartUpdateShippingAddressHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACCartResponse* result
		ACCartResponse* result = (ACCartResponse*)value;
	NSLog(@"CartUpdateShippingAddress returned the value: %@", result);
			
}
	

// Handle the response from CatalogGetFeaturedCategories.
		
- (void) CatalogGetFeaturedCategoriesHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACFeaturedCategoryResponse* result
		ACFeaturedCategoryResponse* result = (ACFeaturedCategoryResponse*)value;
	NSLog(@"CatalogGetFeaturedCategories returned the value: %@", result);
			
}
	

// Handle the response from CatalogItemGet.
		
- (void) CatalogItemGetHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACItemResponse* result
		ACItemResponse* result = (ACItemResponse*)value;
	NSLog(@"CatalogItemGet returned the value: %@", result);
			
}
	

// Handle the response from CatalogItemGetFrameRecommendations.
		
- (void) CatalogItemGetFrameRecommendationsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACItemResponse* result
		ACItemResponse* result = (ACItemResponse*)value;
	NSLog(@"CatalogItemGetFrameRecommendations returned the value: %@", result);
			
}
	

// Handle the response from CatalogItemSearch.
		
- (void) CatalogItemSearchHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACItemSearchResponse* result
		ACItemSearchResponse* result = (ACItemSearchResponse*)value;
	NSLog(@"CatalogItemSearch returned the value: %@", result);
			
}
	

// Handle the response from CatalogItemSearchByImage.
		
- (void) CatalogItemSearchByImageHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACItemSearchResponse* result
		ACItemSearchResponse* result = (ACItemSearchResponse*)value;
	NSLog(@"CatalogItemSearchByImage returned the value: %@", result);
			
}
	

// Handle the response from GalleryAddForUser.
		
- (void) GalleryAddForUserHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACGalleryDetailResponse* result
		ACGalleryDetailResponse* result = (ACGalleryDetailResponse*)value;
	NSLog(@"GalleryAddForUser returned the value: %@", result);
			
}
	

// Handle the response from GalleryAddItem.
		
- (void) GalleryAddItemHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACGalleryDetailResponse* result
		ACGalleryDetailResponse* result = (ACGalleryDetailResponse*)value;
	NSLog(@"GalleryAddItem returned the value: %@", result);
			
}
	

// Handle the response from GalleryAddWallImageByImageGUID.
		
- (void) GalleryAddWallImageByImageGUIDHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACGalleryDetailResponse* result
		ACGalleryDetailResponse* result = (ACGalleryDetailResponse*)value;
	NSLog(@"GalleryAddWallImageByImageGUID returned the value: %@", result);
			
}
	

// Handle the response from GalleryGet.
		
- (void) GalleryGetHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACGalleryDetailResponse* result
		ACGalleryDetailResponse* result = (ACGalleryDetailResponse*)value;
	NSLog(@"GalleryGet returned the value: %@", result);
			
}
	

// Handle the response from GalleryGetByUser.
		
- (void) GalleryGetByUserHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACGalleryListResponse* result
		ACGalleryListResponse* result = (ACGalleryListResponse*)value;
	NSLog(@"GalleryGetByUser returned the value: %@", result);
			
}
	

// Handle the response from GalleryGetUserDefaultMobileGallery.
		
- (void) GalleryGetUserDefaultMobileGalleryHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACGalleryDetailResponse* result
		ACGalleryDetailResponse* result = (ACGalleryDetailResponse*)value;
	NSLog(@"GalleryGetUserDefaultMobileGallery returned the value: %@", result);
			
}
	

// Handle the response from GalleryGetUserDefaultWallGallery.
		
- (void) GalleryGetUserDefaultWallGalleryHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACGalleryDetailResponse* result
		ACGalleryDetailResponse* result = (ACGalleryDetailResponse*)value;
	NSLog(@"GalleryGetUserDefaultWallGallery returned the value: %@", result);
			
}
	

// Handle the response from GalleryRemoveItem.
		
- (void) GalleryRemoveItemHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACGalleryDetailResponse* result
		ACGalleryDetailResponse* result = (ACGalleryDetailResponse*)value;
	NSLog(@"GalleryRemoveItem returned the value: %@", result);
			
}
	

// Handle the response from InitializeAPI.
		
- (void) InitializeAPIHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the ACSessionResponse* result
		ACSessionResponse* result = (ACSessionResponse*)value;
	NSLog(@"InitializeAPI returned the value: %@", result);
			
}
	

@end
		